version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  dev-environment:
    networks: 
      - grid
    build: .
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  chrome:
    image: seleniarm/node-chromium
    networks: 
      - grid
    shm_size: 2gb
    # volumes:
    #   - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=8
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
    # ports:
    #   - "6900:5900"

  # edge:
  #   image: seleniarm/node-edge
  #   networks: 
  #     - grid
  #   shm_size: 2gb
  #   # volumes:
  #   #   - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_NODE_OVERRIDE_MAX_SESSIONS=true
  #     - SE_NODE_MAX_SESSIONS=8
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #     - SE_NODE_GRID_URL=http://selenium-hub:4444
  #   # ports:
  #   #   - "6901:5900"

  firefox:
    image: seleniarm/node-firefox
    networks: 
      - grid
    shm_size: 2gb
    # volumes:
    #   - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=8
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
    # ports:
    #   - "6902:5900"

  selenium-hub:
    image: seleniarm/hub
    networks: 
      - grid
    # container_name: selenium-hub
    # ports:
    #   - "4442:4442"
    #   - "4443:4443"
    #   - "4444:4444"
networks:
  grid: {}

 
